import type { HubContent } from "./types";

export type HubKind = "corporate" | "activity" | "solutions" | "explore" | "service" | "areas" | "knowledge";

export const HUB_CHROME = {
  gridDefaultLabel: "BAŞLIKLAR",
  gridDefaultTitle: "Bu bölümde neler var?",
  more: "İncele",
};

export const HUB_CHROME_EN = {
  gridDefaultLabel: "SECTIONS",
  gridDefaultTitle: "What's in this section?",
  more: "Explore",
};

export function hubChrome(locale: string) {
  return locale === "en" ? HUB_CHROME_EN : HUB_CHROME;
}

export const hubDefaults: Record<HubKind, HubContent> = {
  corporate: {
    eyebrow: "KURUMSAL",
    titleTop: "Köklü bir yapı,",
    titleAccent: "güncel bir bakış.",
    lead: "45 yıllık teknik birikimi kurumsal bir düzene taşıyan Kayahan Isı; geçmişin ustalığını modern mühendislik anlayışıyla birleştirir.",
    image: "/assets/corporate-memory-cgi.png",
    imageAlt: "Kurumsal hafızayı temsil eden cam katmanlar",
    gridHeadLabel: HUB_CHROME.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME.gridDefaultTitle,
    items: [
      { title: "Hakkımızda", href: "/tr/kurumsal/hakkimizda", text: "1976’dan bugüne kısa hikâye ve bugünkü yapı.", icon: "building" },
      { title: "Yönetim Kurulu", href: "/tr/kurumsal/yonetim-kurulu", text: "Tecrübenin yön verdiği, geleceğe açık yönetim.", icon: "users" },
      { title: "Yönetim Kurulu Mesajı", href: "/tr/kurumsal/yonetim-kurulu-mesaji", text: "Geçmişe bağlı, geleceğe hazır bir bakış.", icon: "quote" },
      { title: "Misyon & Vizyon", href: "/tr/kurumsal/misyon-vizyon", text: "Nereden geldik, nereye gidiyoruz.", icon: "target" },
      { title: "Kalite Politikamız", href: "/tr/kurumsal/kalite-politikasi", text: "Ölçülebilir, izlenebilir ve standartlara bağlı hizmet.", icon: "shield" },
      { title: "Sürdürülebilirlik", href: "/tr/kurumsal/surdurulebilirlik", text: "Daha az tüketen, daha uzun ömürlü sistemler.", icon: "leaf" },
    ],
    band: "Ticari faaliyetin ötesinde bir sorumluluk.",
    ctaLabel: "İletişime Geçin",
    ctaHref: "/tr/iletisim",
  },
  activity: {
    eyebrow: "FAALİYET ALANLARIMIZ",
    titleTop: "İklimi, enerjiyi ve",
    titleAccent: "yapıyı birlikte düşünüyoruz.",
    lead: "İklimlendirme, ısıtma, soğutma, yalıtım ve enerji; tek bir mühendislik disiplini altında toplanan beş ana alan.",
    image: "/assets/climate-orchestration-cgi.png",
    imageAlt: "Isı, hava ve enerjiyi birleştiren iklim sistemi",
    gridHeadLabel: HUB_CHROME.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME.gridDefaultTitle,
    items: [
      { title: "İklimlendirme", href: "/tr/faaliyet-alanlari/iklimlendirme", text: "Kontrollü, sağlıklı ve verimli iç ortam.", icon: "wind" },
      { title: "Isıtma", href: "/tr/faaliyet-alanlari/isitma", text: "Güvenli, dengeli ve yüksek verimli ısı yönetimi.", icon: "heat" },
      { title: "Soğutma", href: "/tr/faaliyet-alanlari/sogutma", text: "Yüksek performansı kontrollü tüketimle buluşturan çözümler.", icon: "snow" },
      { title: "Yalıtım", href: "/tr/faaliyet-alanlari/yalitim", text: "Enerji kaybını azaltan, yapıyı koruyan sistem yaklaşımı.", icon: "layers" },
      { title: "Enerji", href: "/tr/faaliyet-alanlari/enerji", text: "Tüketimi ölçen, kayıpları görünür kılan mühendislik.", icon: "zap" },
    ],
    band: "Her yapı için doğru sistem, doğru denge.",
    ctaLabel: "Teklif Alın",
    ctaHref: "/tr/teklif-al",
  },
  solutions: {
    eyebrow: "ÇÖZÜMLERİMİZ",
    titleTop: "Parçaları değil,",
    titleAccent: "bütünü çözüyoruz.",
    lead: "Analizden devreye almaya, bakımdan otomasyona; mekanik sistemleri birlikte çalışan bir performans bütünü olarak tasarlıyoruz.",
    image: "/assets/solution-systems-cgi.png",
    imageAlt: "Sistem çözümleri teknik görselleştirmesi",
    gridHeadLabel: HUB_CHROME.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME.gridDefaultTitle,
    items: [
      { title: "Sistem Çözümleri", href: "/tr/cozumler/sistem-cozumleri", text: "Uçtan uca mühendislik: analiz, tasarım, devreye alma.", icon: "network" },
      { title: "Bina Otomasyonu", href: "/tr/cozumler/bina-otomasyonu", text: "Tek merkezden izleme, kontrol ve raporlama.", icon: "cpu" },
      { title: "Enerji Verimliliği", href: "/tr/cozumler/enerji-verimliligi", text: "Kayıpları görünür kılan, ölçülebilir iyileştirme.", icon: "gauge" },
      { title: "Servis & Bakım", href: "/tr/cozumler/servis-bakim", text: "Sistem ömrü boyunca kesintisiz performans.", icon: "wrench" },
    ],
    band: "Tek bir hedef için çalışan, birbiriyle konuşan sistemler.",
    ctaLabel: "Çözümleri Görüşelim",
    ctaHref: "/tr/iletisim",
  },
  explore: {
    eyebrow: "KEŞFET",
    titleTop: "Sahadan projelere,",
    titleAccent: "belgelerden basına.",
    lead: "Kayahan Isı'yı daha yakından tanıyın: tamamladığımız projeler, kurumsal yeterliliğimizi belgeleyen sertifikalar, saha görselleri ve güncel gelişmeler.",
    image: "/assets/home-media-cgi.png",
    imageAlt: "Kayahan Isı mühendislik ve teknoloji",
    gridHeadLabel: HUB_CHROME.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME.gridDefaultTitle,
    items: [
      { title: "Projelerimiz", href: "/tr/projelerimiz", text: "Analizden devreye almaya, ölçülebilir performans.", icon: "projects" },
      { title: "Sertifikalarımız", href: "/tr/kurumsal/sertifikalarimiz", text: "Standartlara bağlı, belgelendirilmiş yeterlilik.", icon: "certificate" },
      { title: "Galeri", href: "/tr/galeri", text: "Sahadan ve projelerden seçkiler.", icon: "gallery" },
      { title: "Basında Biz", href: "/tr/basinda-biz", text: "Kayahan Isı'dan güncel gelişmeler.", icon: "news" },
    ],
    band: "Kayahan Isı'yı yakından tanıyın.",
    ctaLabel: "İletişime Geçin",
    ctaHref: "/tr/iletisim",
  },
  service: {
    eyebrow: "SERVİS",
    titleTop: "Kombi, klima ve şofben:",
    titleAccent: "aynı gün, belgeli ekip.",
    lead: "45 yıl DemirDöküm ve Vaillant yetkili servisi olarak edindiğimiz deneyimle bugün tüm markalara hizmet veriyoruz. İstanbul Avrupa Yakası'nda sekiz ilçede arıza, bakım, orijinal parça ve montaj — 7/24 ulaşılabilir hat.",
    image: "/assets/servis-filo.webp",
    imageAlt: "Kayahan Isı servis filosu — merkez bina önünde servis araçları",
    gridHeadLabel: "HİZMETLERİMİZ",
    gridHeadTitle: "Cihazınızı seçin.",
    items: [
      { title: "Kombi Servisi", href: "/tr/kombi-servisi", text: "Arıza, yıllık bakım, orijinal parça, montaj ve yoğuşmalıya dönüşüm.", icon: "heat" },
      { title: "Klima Servisi", href: "/tr/klima-servisi", text: "Bakım, gaz dolumu, kaçak tespiti, montaj ve söküm-takım.", icon: "snow" },
      { title: "Şofben Servisi", href: "/tr/sofben-servisi", text: "Gazlı ve elektrikli modellerde arıza, bakım ve mevzuata uygun montaj.", icon: "zap" },
    ],
    band: "Sekiz ilçede aynı gün servis — hizmet bölgelerimizi ve markaya göre servis sayfalarımızı inceleyin.",
    ctaLabel: "Hizmet bölgelerimiz",
    ctaHref: "/tr/hizmet-bolgelerimiz",
  },
  areas: {
    eyebrow: "HİZMET BÖLGELERİMİZ",
    titleTop: "İstanbul Avrupa Yakası'nda",
    titleAccent: "sekiz ilçe, aynı gün.",
    lead: "Merkezimiz Bahçelievler'de; ekiplerimiz sekiz ilçede konumlanır ve size en yakın teknisyen yönlendirilir. İlçenizi seçin, o bölgede en sık yaptığımız işleri ve mahalleleri görün.",
    image: "/gallery/vip-kurumsal-servis-araci.webp",
    imageAlt: "Kayahan Isı servis aracı",
    gridHeadLabel: "İLÇELER",
    gridHeadTitle: "İlçenizi seçin.",
    items: [
      { title: "Bahçelievler", href: "/tr/servis/bahcelievler", text: "Merkezimiz; Şirinevler, Yenibosna, Kocasinan, Siyavuşpaşa, Soğanlı.", icon: "target" },
      { title: "Bağcılar", href: "/tr/servis/bagcilar", text: "Güneşli, Mahmutbey, Yenimahalle, Kirazlı, Göztepe.", icon: "target" },
      { title: "Bakırköy", href: "/tr/servis/bakirkoy", text: "Ataköy, Florya, Yeşilköy, Yeşilyurt, Osmaniye.", icon: "target" },
      { title: "Güngören", href: "/tr/servis/gungoren", text: "Merter, Tozkoparan, Haznedar, Güneştepe.", icon: "target" },
      { title: "Zeytinburnu", href: "/tr/servis/zeytinburnu", text: "Kazlıçeşme, Merkezefendi, Beştelsiz, Sümer, Telsiz.", icon: "target" },
      { title: "Esenler", href: "/tr/servis/esenler", text: "Atışalanı, Oruçreis, Menderes, Kemer, Havaalanı.", icon: "target" },
      { title: "Bayrampaşa", href: "/tr/servis/bayrampasa", text: "Kocatepe, Yıldırım, Altıntepsi, Terazidere, Vatan.", icon: "target" },
      { title: "Küçükçekmece", href: "/tr/servis/kucukcekmece", text: "Halkalı, Atakent, Sefaköy, Tevfikbey, Cennet.", icon: "target" },
    ],
    band: "Listede olmayan bir ilçedeyseniz arayın; komşu ilçelere de uygunluğa göre servis veriyoruz.",
    ctaLabel: "Servis talebi oluştur",
    ctaHref: "/tr/teklif-al",
  },
  knowledge: {
    eyebrow: "BİLGİ MERKEZİ",
    titleTop: "Bilgiyi paylaşır.",
    titleAccent: "Geleceği geliştiririz.",
    lead: "Sahadan gelen teknik deneyimi, sık sorulan soruları ve müşteri deneyimlerini tek yerde topluyoruz: rehber yazılar, doğrudan yanıtlar ve gerçek hikâyeler.",
    image: "/assets/knowledge-hub-art.svg",
    imageAlt: "Bilgi merkezi — bilgi ağı illüstrasyonu",
    gridHeadLabel: HUB_CHROME.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME.gridDefaultTitle,
    items: [
      { title: "Blog", href: "/tr/blog", text: "Isıtma, soğutma ve enerji verimliliği üzerine rehber yazılar.", icon: "news" },
      { title: "Sıkça Sorulan Sorular", href: "/tr/sikca-sorulan-sorular", text: "Servis, bakım ve montaj hakkında doğrudan yanıtlar.", icon: "quote" },
      { title: "Müşteri Yorumları", href: "/tr/musteri-yorumlari", text: "Birlikte tamamladığımız işlerden gerçek deneyimler.", icon: "users" },
    ],
    band: "Aradığınız yanıtı bulamadıysanız 7/24 hattımızdan bize ulaşın.",
    ctaLabel: "İletişime geçin",
    ctaHref: "/tr/iletisim",
  },
};

export const hubDefaultsEn: Record<HubKind, HubContent> = {
  corporate: {
    eyebrow: "CORPORATE",
    titleTop: "A rooted structure,",
    titleAccent: "a current outlook.",
    lead: "Kayahan Isı carries 45 years of technical know-how into a corporate order, joining the craftsmanship of the past with a modern engineering mindset.",
    image: "/assets/corporate-memory-cgi.png",
    imageAlt: "Glass layers representing corporate memory",
    gridHeadLabel: HUB_CHROME_EN.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME_EN.gridDefaultTitle,
    items: [
      { title: "About Us", href: "/en/kurumsal/hakkimizda", text: "The short story since 1976 and today's structure.", icon: "building" },
      { title: "Board of Directors", href: "/en/kurumsal/yonetim-kurulu", text: "A board guided by experience, open to the future.", icon: "users" },
      { title: "Message from the Board", href: "/en/kurumsal/yonetim-kurulu-mesaji", text: "Rooted in the past, ready for the future.", icon: "quote" },
      { title: "Mission & Vision", href: "/en/kurumsal/misyon-vizyon", text: "Where we come from, where we are heading.", icon: "target" },
      { title: "Quality Policy", href: "/en/kurumsal/kalite-politikasi", text: "Measurable, traceable, standards-based service.", icon: "shield" },
      { title: "Sustainability", href: "/en/kurumsal/surdurulebilirlik", text: "Systems that consume less and last longer.", icon: "leaf" },
    ],
    band: "A responsibility beyond commercial activity.",
    ctaLabel: "Get in Touch",
    ctaHref: "/en/iletisim",
  },
  activity: {
    eyebrow: "OUR FIELDS",
    titleTop: "We think about climate, energy",
    titleAccent: "and the building together.",
    lead: "Air conditioning, heating, cooling, insulation and energy — five core fields brought together under a single engineering discipline.",
    image: "/assets/climate-orchestration-cgi.png",
    imageAlt: "A climate system combining heat, air and energy",
    gridHeadLabel: HUB_CHROME_EN.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME_EN.gridDefaultTitle,
    items: [
      { title: "Air Conditioning", href: "/en/faaliyet-alanlari/iklimlendirme", text: "Controlled, healthy and efficient indoor climate.", icon: "wind" },
      { title: "Heating", href: "/en/faaliyet-alanlari/isitma", text: "Safe, balanced and highly efficient heat management.", icon: "heat" },
      { title: "Cooling", href: "/en/faaliyet-alanlari/sogutma", text: "Solutions that pair high performance with controlled consumption.", icon: "snow" },
      { title: "Insulation", href: "/en/faaliyet-alanlari/yalitim", text: "A system approach that cuts energy loss and protects the building.", icon: "layers" },
      { title: "Energy", href: "/en/faaliyet-alanlari/enerji", text: "Engineering that measures consumption and makes losses visible.", icon: "zap" },
    ],
    band: "The right system, the right balance, for every building.",
    ctaLabel: "Get a Quote",
    ctaHref: "/en/teklif-al",
  },
  solutions: {
    eyebrow: "OUR SOLUTIONS",
    titleTop: "We solve not the parts,",
    titleAccent: "but the whole.",
    lead: "From analysis to commissioning, from maintenance to automation — we design mechanical systems as one performance whole that works together.",
    image: "/assets/solution-systems-cgi.png",
    imageAlt: "System solutions technical visualisation",
    gridHeadLabel: HUB_CHROME_EN.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME_EN.gridDefaultTitle,
    items: [
      { title: "System Solutions", href: "/en/cozumler/sistem-cozumleri", text: "End-to-end engineering: analysis, design, commissioning.", icon: "network" },
      { title: "Building Automation", href: "/en/cozumler/bina-otomasyonu", text: "Monitor, control and report from one place.", icon: "cpu" },
      { title: "Energy Efficiency", href: "/en/cozumler/enerji-verimliligi", text: "Measurable improvement that makes losses visible.", icon: "gauge" },
      { title: "Service & Maintenance", href: "/en/cozumler/servis-bakim", text: "Uninterrupted performance across the system's life.", icon: "wrench" },
    ],
    band: "Systems that talk to each other, working toward a single goal.",
    ctaLabel: "Let's Talk Solutions",
    ctaHref: "/en/iletisim",
  },
  explore: {
    eyebrow: "EXPLORE",
    titleTop: "From the field to projects,",
    titleAccent: "from certificates to the press.",
    lead: "Get to know Kayahan Isı more closely: the projects we've completed, the certificates documenting our corporate competence, field imagery and the latest developments.",
    image: "/assets/home-media-cgi.png",
    imageAlt: "Kayahan Isı engineering and technology",
    gridHeadLabel: HUB_CHROME_EN.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME_EN.gridDefaultTitle,
    items: [
      { title: "Our Projects", href: "/en/projelerimiz", text: "From analysis to commissioning, measurable performance.", icon: "projects" },
      { title: "Certifications", href: "/en/kurumsal/sertifikalarimiz", text: "Standards-based, certified competence.", icon: "certificate" },
      { title: "Gallery", href: "/en/galeri", text: "A selection from the field and from projects.", icon: "gallery" },
      { title: "In the Press", href: "/en/basinda-biz", text: "Latest developments from Kayahan Isı.", icon: "news" },
    ],
    band: "Get to know Kayahan Isı up close.",
    ctaLabel: "Get in Touch",
    ctaHref: "/en/iletisim",
  },
  service: {
    eyebrow: "SERVICE",
    titleTop: "Boiler, AC and water heater:",
    titleAccent: "same day, certified team.",
    lead: "With 45 years as DemirDöküm and Vaillant authorised service behind us, we now serve every brand across eight districts on Istanbul's European side — repair, maintenance, genuine parts and installation, 24/7.",
    image: "/assets/servis-filo.webp",
    imageAlt: "Kayahan Isı service fleet in front of the head office",
    gridHeadLabel: "OUR SERVICES",
    gridHeadTitle: "Pick your appliance.",
    items: [
      { title: "Boiler Service", href: "/en/kombi-servisi", text: "Faults, annual maintenance, genuine parts, installation and condensing conversion.", icon: "heat" },
      { title: "AC Service", href: "/en/klima-servisi", text: "Maintenance, refrigerant charging, leak detection, installation and relocation.", icon: "snow" },
      { title: "Water-Heater Service", href: "/en/sofben-servisi", text: "Gas and electric models — faults, maintenance, code-compliant installation.", icon: "zap" },
    ],
    band: "Same-day service in eight districts — see our service areas and service-by-brand pages.",
    ctaLabel: "Service areas",
    ctaHref: "/en/hizmet-bolgelerimiz",
  },
  areas: {
    eyebrow: "SERVICE AREAS",
    titleTop: "Eight districts on Istanbul's",
    titleAccent: "European side, same day.",
    lead: "Our base is in Bahçelievler; teams are placed across eight districts and the nearest technician is dispatched. Pick your district to see typical jobs and neighbourhoods.",
    image: "/gallery/vip-kurumsal-servis-araci.webp",
    imageAlt: "Kayahan Isı service van",
    gridHeadLabel: "DISTRICTS",
    gridHeadTitle: "Pick your district.",
    items: [
      { title: "Bahçelievler", href: "/en/servis/bahcelievler", text: "Our base; Şirinevler, Yenibosna, Kocasinan, Siyavuşpaşa, Soğanlı.", icon: "target" },
      { title: "Bağcılar", href: "/en/servis/bagcilar", text: "Güneşli, Mahmutbey, Yenimahalle, Kirazlı, Göztepe.", icon: "target" },
      { title: "Bakırköy", href: "/en/servis/bakirkoy", text: "Ataköy, Florya, Yeşilköy, Yeşilyurt, Osmaniye.", icon: "target" },
      { title: "Güngören", href: "/en/servis/gungoren", text: "Merter, Tozkoparan, Haznedar, Güneştepe.", icon: "target" },
      { title: "Zeytinburnu", href: "/en/servis/zeytinburnu", text: "Kazlıçeşme, Merkezefendi, Beştelsiz, Sümer, Telsiz.", icon: "target" },
      { title: "Esenler", href: "/en/servis/esenler", text: "Atışalanı, Oruçreis, Menderes, Kemer, Havaalanı.", icon: "target" },
      { title: "Bayrampaşa", href: "/en/servis/bayrampasa", text: "Kocatepe, Yıldırım, Altıntepsi, Terazidere, Vatan.", icon: "target" },
      { title: "Küçükçekmece", href: "/en/servis/kucukcekmece", text: "Halkalı, Atakent, Sefaköy, Tevfikbey, Cennet.", icon: "target" },
    ],
    band: "Not in the list? Call us — neighbouring districts are served subject to availability.",
    ctaLabel: "Request service",
    ctaHref: "/en/teklif-al",
  },
  knowledge: {
    eyebrow: "KNOWLEDGE HUB",
    titleTop: "Sharing knowledge.",
    titleAccent: "Advancing the future.",
    lead: "Field experience, frequently asked questions and client stories in one place: guides, straight answers and real experiences.",
    image: "/assets/knowledge-hub-art.svg",
    imageAlt: "Knowledge hub — knowledge network illustration",
    gridHeadLabel: HUB_CHROME_EN.gridDefaultLabel,
    gridHeadTitle: HUB_CHROME_EN.gridDefaultTitle,
    items: [
      { title: "Blog", href: "/en/blog", text: "Guides on heating, cooling and energy efficiency.", icon: "news" },
      { title: "FAQ", href: "/en/sikca-sorulan-sorular", text: "Straight answers on service, maintenance and installation.", icon: "quote" },
      { title: "Client Stories", href: "/en/musteri-yorumlari", text: "Real experiences from completed work.", icon: "users" },
    ],
    band: "Can't find the answer? Reach us 24/7.",
    ctaLabel: "Contact us",
    ctaHref: "/en/iletisim",
  },
};
