import type { SolutionContent } from "./types";

export type SolutionKind = "systems" | "automation" | "efficiency" | "service";

/** Section furniture shared by all four solution pages. */
export const SOLUTION_CHROME = {
  heroCta: "ÇÖZÜM MİMARİSİ",
  indexBand: ["ÇÖZÜM", "ANALİZ", "ENTEGRASYON", "PERFORMANS"] as const,
  thesisLabel: "ÇÖZÜM PRENSİBİ",
  archLabel: "UÇTAN UCA SÜREÇ",
  archTitleTop: "Her adım,",
  archTitleAccent: "bir sonrakini besler.",
  outputLabel: "ÇÖZÜM KAPSAMI",
  outputTitleTop: "Projeye özel,",
  outputTitleAccent: "ölçülebilir çıktılar.",
};

export const SOLUTION_CHROME_EN = {
  heroCta: "SOLUTION ARCHITECTURE",
  indexBand: ["SOLUTION", "ANALYSIS", "INTEGRATION", "PERFORMANCE"] as const,
  thesisLabel: "SOLUTION PRINCIPLE",
  archLabel: "END-TO-END PROCESS",
  archTitleTop: "Every step",
  archTitleAccent: "feeds the next.",
  outputLabel: "SOLUTION SCOPE",
  outputTitleTop: "Project-specific,",
  outputTitleAccent: "measurable outputs.",
};

export function solutionChrome(locale: string) {
  return locale === "en" ? SOLUTION_CHROME_EN : SOLUTION_CHROME;
}

export const solutionDefaults: Record<SolutionKind, SolutionContent> = {
  systems: {
    index: "01 / SİSTEM ÇÖZÜMLERİ",
    name: "Sistem Çözümleri",
    slug: "/tr/cozumler/sistem-cozumleri",
    asset: "/assets/solution-systems-cgi.png",
    assetAlt: "Sistem Çözümleri teknik görselleştirmesi",
    titleTop: "Parçaları değil,",
    titleAccent: "bütünü çözüyoruz.",
    lead: "Mekanik sistemleri tek tek bileşenler olarak değil, birlikte çalışan bir performans mimarisi olarak tasarlıyoruz.",
    ctaLabel: SOLUTION_CHROME.heroCta,
    thesis: "Tek bir hedef için çalışan, birbiriyle konuşan sistemler.",
    text: "Isıtma, soğutma, havalandırma, hidrolik dağıtım ve kontrol katmanlarını aynı proje aklında buluşturuyoruz. Böylece yatırım kararından işletmeye kadar bütün sistem tutarlı çalışıyor.",
    stages: [
      { title: "Analiz", text: "Yapının yükleri ve kullanım senaryosu." },
      { title: "Mimari", text: "Bileşenlerin ortak sistem kurgusu." },
      { title: "Entegrasyon", text: "Mekanik ve kontrol katmanlarının uyumu." },
      { title: "Doğrulama", text: "Devreye alma ve performans kontrolü." },
    ],
    outputs: [
      "Mekanik sistem tasarımı",
      "Ekipman ve kapasite seçimi",
      "Hidrolik dengeleme",
      "Devreye alma koordinasyonu",
    ],
  },
  automation: {
    index: "02 / BİNA OTOMASYONU",
    name: "Bina Otomasyonu",
    slug: "/tr/cozumler/bina-otomasyonu",
    asset: "/assets/solution-automation-cgi.png",
    assetAlt: "Bina Otomasyonu teknik görselleştirmesi",
    titleTop: "Yapınız düşünsün.",
    titleAccent: "Sisteminiz uyum sağlasın.",
    lead: "Sensör, kontrol ve izleme katmanlarını tek merkezde birleştiren akıllı bina otomasyonu.",
    ctaLabel: SOLUTION_CHROME.heroCta,
    thesis: "Her veriyi doğru karara dönüştüren canlı bir kontrol katmanı.",
    text: "Saha ekipmanından yönetim ekranına kadar tüm veri akışını kurguluyor; değişen yüklere tepki veren, kullanıcıya görünürlük ve kontrol sağlayan otomasyon sistemleri kuruyoruz.",
    stages: [
      { title: "Algıla", text: "Sıcaklık, basınç, debi ve enerji verisi." },
      { title: "Yorumla", text: "Kural ve senaryolarla gerçek zamanlı analiz." },
      { title: "Kontrol et", text: "Ekipman ve zon bazlı hassas müdahale." },
      { title: "Öğren", text: "İşletme verisiyle sürekli optimizasyon." },
    ],
    outputs: [
      "BMS sistem mimarisi",
      "Sensör ve kontrol senaryoları",
      "Uzaktan izleme",
      "Alarm ve raporlama",
    ],
  },
  efficiency: {
    index: "03 / ENERJİ VERİMLİLİĞİ",
    name: "Enerji Verimliliği",
    slug: "/tr/cozumler/enerji-verimliligi",
    asset: "/assets/solution-efficiency-cgi.png",
    assetAlt: "Enerji Verimliliği teknik görselleştirmesi",
    titleTop: "Kayıpları görünür kıl.",
    titleAccent: "Enerjiyi geri kazan.",
    lead: "Tüketimi azaltırken konforu ve üretkenliği koruyan ölçülebilir verimlilik çözümleri.",
    ctaLabel: SOLUTION_CHROME.heroCta,
    thesis: "Tasarruf değil; kalıcı ve doğrulanabilir performans.",
    text: "Tüketim profilini, çalışma saatlerini ve sistem davranışını birlikte inceliyor; geri kazanım ve optimizasyon fırsatlarını yatırım önceliğine göre sıralıyoruz.",
    stages: [
      { title: "Ölç", text: "Tüketimin sistem ve zaman bazlı görünürlüğü." },
      { title: "Karşılaştır", text: "Referans değer ve gerçek performans farkı." },
      { title: "İyileştir", text: "Kayıpları azaltan teknik müdahaleler." },
      { title: "Doğrula", text: "Sonucun düzenli izlenmesi ve raporlanması." },
    ],
    outputs: [
      "Enerji performans analizi",
      "Isı geri kazanımı",
      "Pompa ve fan optimizasyonu",
      "Tüketim izleme",
    ],
  },
  service: {
    index: "04 / SERVİS & BAKIM",
    name: "Servis & Bakım",
    slug: "/tr/cozumler/servis-bakim",
    asset: "/assets/solution-service-cgi.png",
    assetAlt: "Servis & Bakım teknik görselleştirmesi",
    titleTop: "Performans,",
    titleAccent: "teslimle bitmez.",
    lead: "Sistemin ömrü boyunca güvenilir, verimli ve kesintisiz çalışmasını koruyan teknik servis yaklaşımı.",
    ctaLabel: SOLUTION_CHROME.heroCta,
    thesis: "Sorun oluştuğunda değil, performans değiştiğinde harekete geçmek.",
    text: "Periyodik bakım, uzaktan izleme ve performans kontrolleriyle arızaları oluşmadan öngörüyor; ekipmanın ömrünü ve sistem verimini birlikte koruyoruz.",
    stages: [
      { title: "İzle", text: "Çalışma değerleri ve alarm geçmişi." },
      { title: "Teşhis et", text: "Sapma ve kayıp kaynaklarının tespiti." },
      { title: "Müdahale et", text: "Planlı, hızlı ve kayıtlı servis." },
      { title: "Koru", text: "Bakım verisiyle uzun vadeli performans." },
    ],
    outputs: [
      "Periyodik bakım",
      "Arıza teşhisi",
      "Performans ayarı",
      "Yedek parça planlaması",
    ],
  },
};

export const solutionDefaultsEn: Record<SolutionKind, SolutionContent> = {
  systems: {
    index: "01 / SYSTEM SOLUTIONS",
    name: "System Solutions",
    slug: "/en/cozumler/sistem-cozumleri",
    asset: "/assets/solution-systems-cgi.png",
    assetAlt: "System Solutions technical visualisation",
    titleTop: "We solve not the parts,",
    titleAccent: "but the whole.",
    lead: "We design mechanical systems not as individual components but as a performance architecture that works together.",
    ctaLabel: SOLUTION_CHROME_EN.heroCta,
    thesis: "Systems that talk to each other, working toward a single goal.",
    text: "We bring heating, cooling, ventilation, hydraulic distribution and control layers into one project mindset, so the whole system runs consistently from the investment decision through to operation.",
    stages: [
      { title: "Analysis", text: "The building's loads and usage scenario." },
      { title: "Architecture", text: "A shared system layout for the components." },
      { title: "Integration", text: "Alignment of the mechanical and control layers." },
      { title: "Validation", text: "Commissioning and performance checks." },
    ],
    outputs: [
      "Mechanical system design",
      "Equipment and capacity selection",
      "Hydraulic balancing",
      "Commissioning coordination",
    ],
  },
  automation: {
    index: "02 / BUILDING AUTOMATION",
    name: "Building Automation",
    slug: "/en/cozumler/bina-otomasyonu",
    asset: "/assets/solution-automation-cgi.png",
    assetAlt: "Building Automation technical visualisation",
    titleTop: "Let your building think.",
    titleAccent: "Let your system adapt.",
    lead: "Smart building automation that unifies sensing, control and monitoring layers in a single hub.",
    ctaLabel: SOLUTION_CHROME_EN.heroCta,
    thesis: "A living control layer that turns every data point into the right decision.",
    text: "We design the whole data flow from field equipment to the management screen, building automation systems that respond to changing loads and give the user visibility and control.",
    stages: [
      { title: "Sense", text: "Temperature, pressure, flow and energy data." },
      { title: "Interpret", text: "Real-time analysis with rules and scenarios." },
      { title: "Control", text: "Precise, equipment- and zone-level intervention." },
      { title: "Learn", text: "Continuous optimisation with operating data." },
    ],
    outputs: [
      "BMS system architecture",
      "Sensor and control scenarios",
      "Remote monitoring",
      "Alarms and reporting",
    ],
  },
  efficiency: {
    index: "03 / ENERGY EFFICIENCY",
    name: "Energy Efficiency",
    slug: "/en/cozumler/enerji-verimliligi",
    asset: "/assets/solution-efficiency-cgi.png",
    assetAlt: "Energy Efficiency technical visualisation",
    titleTop: "Make losses visible.",
    titleAccent: "Recover the energy.",
    lead: "Measurable efficiency solutions that cut consumption while protecting comfort and productivity.",
    ctaLabel: SOLUTION_CHROME_EN.heroCta,
    thesis: "Not savings — lasting, verifiable performance.",
    text: "We examine the consumption profile, operating hours and system behaviour together, then rank recovery and optimisation opportunities by investment priority.",
    stages: [
      { title: "Measure", text: "Consumption visibility by system and by time." },
      { title: "Compare", text: "The gap between the reference value and real performance." },
      { title: "Improve", text: "Technical interventions that reduce losses." },
      { title: "Verify", text: "Regular monitoring and reporting of the result." },
    ],
    outputs: [
      "Energy performance analysis",
      "Heat recovery",
      "Pump and fan optimisation",
      "Consumption monitoring",
    ],
  },
  service: {
    index: "04 / SERVICE & MAINTENANCE",
    name: "Service & Maintenance",
    slug: "/en/cozumler/servis-bakim",
    asset: "/assets/solution-service-cgi.png",
    assetAlt: "Service & Maintenance technical visualisation",
    titleTop: "Performance",
    titleAccent: "does not end at handover.",
    lead: "A technical-service approach that keeps the system reliable, efficient and uninterrupted throughout its life.",
    ctaLabel: SOLUTION_CHROME_EN.heroCta,
    thesis: "Acting when performance changes — not when a fault appears.",
    text: "With periodic maintenance, remote monitoring and performance checks we anticipate faults before they occur, protecting both equipment life and system efficiency.",
    stages: [
      { title: "Monitor", text: "Operating values and alarm history." },
      { title: "Diagnose", text: "Identifying deviations and sources of loss." },
      { title: "Intervene", text: "Planned, fast and recorded service." },
      { title: "Protect", text: "Long-term performance with maintenance data." },
    ],
    outputs: [
      "Periodic maintenance",
      "Fault diagnosis",
      "Performance tuning",
      "Spare-parts planning",
    ],
  },
};
